---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: naked-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: app
    nodePort: 31047
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: naked
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: naked-bardin-haus-vhost
  annotations:
    ingress.class: wkndr
spec:
  rules:
  - host: naked.bardin.haus
    http:
      paths:
      - backend:
          serviceName: naked-service
          servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naked
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      name: naked
  replicas: 1
  template:
    metadata:
      labels:
        name: naked
    spec:
      containers:
      - name: naked-bardin-haus-app
        image: naked.bardin.haus-naked:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command:
        - "bundle"
        - "exec"
        - "puma"
        - "-C"
        - "puma.rb"
        env: &1
        - name: APP_ENV
          value: production
